modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="stormlight_mod"
version="1.0.0"
displayName="Stormlight Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="davidmurdock, MCreator"

[[dependencies.stormlight_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




